apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: kube-system
spec:
  serviceAccountName: cluster-autoscaler
  containers:
  - name: test-pod
    image: amazon/aws-cli
    command: ["sleep", "infinity"]
  restartPolicy: Never
