---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: test-secrets-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::340752802272:role/staging-demo-myapp-secrets